"""Cinematic taxonomy — EyeCandy-inspired technique library + classic shot DNA.

Techniques are the primary browse axis (like eyecannndy.com). Shot type / movement /
angle remain classic framing properties. Tags stay freeform for subject/era/brand.
"""

from __future__ import annotations

import re

# ---------------------------------------------------------------------------
# Framing — classic shot size
# ---------------------------------------------------------------------------
SHOT_TYPES = [
    "extreme-wide",
    "ultra-wide",
    "wide",
    "full",
    "medium-wide",
    "medium",
    "medium-close-up",
    "close-up",
    "extreme-close-up",
    "insert",
    "detail",
    "two-shot",
    "group",
    "aerial",
    "drone",
    "fpv-drone",
    "pov",
    "object-pov",
    "over-shoulder",
    "profile",
    "product",
    "tableau",
    "other",
]

# ---------------------------------------------------------------------------
# Camera movement
# ---------------------------------------------------------------------------
CAMERA_MOVEMENTS = [
    "static",
    "locked-on",
    "pan",
    "tilt",
    "pedestal",
    "dolly-in",
    "dolly-out",
    "crash-dolly",
    "double-dolly",
    "tracking",
    "trucking",
    "arc",
    "orbit",
    "crane",
    "jib",
    "handheld",
    "steadicam",
    "gimbal",
    "snorricam",
    "bolt-cam",
    "lazy-susan",
    "zoom-in",
    "zoom-out",
    "dolly-zoom",
    "whip-pan",
    "push-in",
    "pull-out",
    "wandering",
    "parallax",
    "pass-through",
    "falling",
    "other",
]

# ---------------------------------------------------------------------------
# Camera angle
# ---------------------------------------------------------------------------
CAMERA_ANGLES = [
    "eye-level",
    "low-angle",
    "high-angle",
    "birds-eye",
    "worms-eye",
    "dutch",
    "overhead",
    "ground-level",
    "profile",
    "three-quarter",
    "canted",
    "other",
]

# ---------------------------------------------------------------------------
# Lighting
# ---------------------------------------------------------------------------
LIGHTING_STYLES = [
    "natural",
    "high-key",
    "low-key",
    "hard-light",
    "soft-diffused",
    "neon",
    "practical",
    "motivated",
    "silhouette",
    "spotlight",
    "golden-hour",
    "blue-hour",
    "overcast",
    "hard-sun",
    "rim-light",
    "chiaroscuro",
    "haze",
    "halation",
    "light-flash",
    "mixed",
    "other",
]

# ---------------------------------------------------------------------------
# Composition (primary framing / spatial design of the still)
# ---------------------------------------------------------------------------
COMPOSITIONS = [
    # Classic grids & ratios
    "rule-of-thirds",
    "golden-ratio",
    "golden-spiral",
    "golden-triangle",
    "centered",
    "central-framing",
    "off-center",
    "symmetry",
    "asymmetry",
    # Letter / curve compositions
    "s-curve",
    "l-composition",
    "c-composition",
    "z-composition",
    "x-composition",
    "triangular",
    "pyramid",
    "circular",
    "radial",
    # Perspective & depth
    "one-point-perspective",
    "two-point-perspective",
    "three-point-perspective",
    "vanishing-point",
    "converging-lines",
    "leading-lines",
    "parallel-lines",
    "diagonal",
    "deep-space",
    "flat-space",
    "layered",
    "overlapping",
    "foreground-interest",
    # Framing devices
    "frame-within-frame",
    "tunnel",
    "corridor",
    "negative-space",
    "fill-the-frame",
    "isolation",
    "open-frame",
    "closed-frame",
    # Balance & density
    "balanced",
    "unbalanced",
    "minimal",
    "crowded",
    "pattern",
    "repetition",
    "breaking-pattern",
    # Subject placement / eye-line
    "looking-room",
    "lead-room",
    "headroom",
    "short-side",
    "horizon-low",
    "horizon-high",
    "horizon-center",
    # Graphic / editorial
    "juxtaposition",
    "silhouette",
    "reflection",
    "mirror",
    "split-screen",
    "screen-in-screen",
    "match-cut",
    "other",
]

COMPOSITION_ALIASES = {
    "s-comp": "s-curve",
    "s-composition": "s-curve",
    "s-curve-composition": "s-curve",
    "golden": "golden-ratio",
    "golden-section": "golden-ratio",
    "phi": "golden-ratio",
    "fibonacci": "golden-spiral",
    "fibonacci-spiral": "golden-spiral",
    "thirds": "rule-of-thirds",
    "rot": "rule-of-thirds",
    "center": "centered",
    "centre": "centered",
    "centre-framing": "central-framing",
    "center-framing": "central-framing",
    "central": "central-framing",
    "symmetrical": "symmetry",
    "asymmetric": "asymmetry",
    "asymmetric-balance": "unbalanced",
    "dynamic-balance": "unbalanced",
    "single-point-perspective": "one-point-perspective",
    "1-point-perspective": "one-point-perspective",
    "one-point": "one-point-perspective",
    "2-point-perspective": "two-point-perspective",
    "two-point": "two-point-perspective",
    "3-point-perspective": "three-point-perspective",
    "three-point": "three-point-perspective",
    "perspective": "one-point-perspective",
    "linear-perspective": "one-point-perspective",
    "vanishing": "vanishing-point",
    "triangle": "triangular",
    "triangle-composition": "triangular",
    "pyramid-composition": "pyramid",
    "circle": "circular",
    "radial-composition": "radial",
    "l-shape": "l-composition",
    "c-shape": "c-composition",
    "z-shape": "z-composition",
    "x-shape": "x-composition",
    "leading-line": "leading-lines",
    "guide-lines": "leading-lines",
    "diagonal-lines": "diagonal",
    "deep-staging": "deep-space",
    "deep-composition": "deep-space",
    "flat-composition": "flat-space",
    "layers": "layered",
    "foreground": "foreground-interest",
    "frame-in-frame": "frame-within-frame",
    "frames-within-frames": "frame-within-frame",
    "mise-en-abyme": "frame-within-frame",
    "negative": "negative-space",
    "empty-space": "negative-space",
    "whitespace": "negative-space",
    "fill-frame": "fill-the-frame",
    "tight-framing": "fill-the-frame",
    "isolated": "isolation",
    "open-composition": "open-frame",
    "closed-composition": "closed-frame",
    "balance": "balanced",
    "imbalance": "unbalanced",
    "sparse": "minimal",
    "busy": "crowded",
    "dense": "crowded",
    "repeating": "repetition",
    "broken-pattern": "breaking-pattern",
    "nose-room": "looking-room",
    "leadspace": "lead-room",
    "leading-room": "lead-room",
    "short-siding": "short-side",
    "shortside": "short-side",
    "low-horizon": "horizon-low",
    "high-horizon": "horizon-high",
    "centered-horizon": "horizon-center",
    "centre-horizon": "horizon-center",
    "silhouette-composition": "silhouette",
    "reflection-composition": "reflection",
    "mirror-composition": "mirror",
    "mirrored": "mirror",
    "split": "split-screen",
}

# ---------------------------------------------------------------------------
# Lens / optical look
# ---------------------------------------------------------------------------
LENS_LOOKS = [
    "wide-angle",
    "ultra-wide",
    "normal",
    "telephoto",
    "anamorphic",
    "macro",
    "probe",
    "fisheye",
    "shallow-dof",
    "deep-focus",
    "split-diopter",
    "tilt-shift",
    "motion-blur",
    "other",
]

# ---------------------------------------------------------------------------
# Color grade
# ---------------------------------------------------------------------------
COLOR_GRADES = [
    "natural",
    "teal-orange",
    "desaturated",
    "warm",
    "cool",
    "high-contrast",
    "pastel",
    "monochrome",
    "neon",
    "bleach-bypass",
    "vintage",
    "color-shift",
    "thermal",
    "night-vision",
    "other",
]

# ---------------------------------------------------------------------------
# Mood / emotion / format
# ---------------------------------------------------------------------------
EMOTIONS = [
    "melancholic",
    "tense",
    "hopeful",
    "euphoric",
    "lonely",
    "intimate",
    "violent",
    "serene",
    "nostalgic",
    "anxious",
    "triumphant",
    "dreamy",
    "cold",
    "warm",
    "uncanny",
    "playful",
    "other",
]

CONTENT_FORMATS = [
    "ad",
    "commercial",
    "film",
    "short-film",
    "music-video",
    "documentary",
    "fashion",
    "sports",
    "social",
    "trailer",
    "title-card",
    "bts",
    "anime",
    "other",
]

# ---------------------------------------------------------------------------
# Eras / decades / cultural moments (film history + period look)
# ---------------------------------------------------------------------------
ERAS = [
    "silent-era",
    "pre-code",
    "1920s",
    "1930s",
    "1940s",
    "golden-age",
    "1950s",
    "1960s",
    "new-hollywood",
    "1970s",
    "80s",
    "90s",
    "y2k",
    "2000s",
    "2010s",
    "2020s",
    "retro-future",
    "period-piece",
    "ancient",
    "medieval",
    "renaissance",
    "victorian",
    "edwardian",
    "belle-epoque",
    "interwar",
    "postwar",
    "cold-war",
    "swinging-sixties",
    "disco-era",
    "mtv-era",
    "digital-age",
    "contemporary",
    "timeless",
    "other",
]

# ---------------------------------------------------------------------------
# Origins / national & regional cinema
# ---------------------------------------------------------------------------
ORIGINS = [
    "hollywood",
    "british",
    "irish",
    "french",
    "italian",
    "german",
    "austrian",
    "scandinavian",
    "swedish",
    "danish",
    "norwegian",
    "finnish",
    "spanish",
    "portuguese",
    "eastern-european",
    "polish",
    "czech",
    "hungarian",
    "russian",
    "soviet",
    "japanese",
    "korean",
    "chinese",
    "hong-kong",
    "taiwanese",
    "thai",
    "vietnamese",
    "filipino",
    "indonesian",
    "indian",
    "iranian",
    "turkish",
    "middle-eastern",
    "israeli",
    "african",
    "north-african",
    "nigerian",
    "south-african",
    "latin-american",
    "brazilian",
    "mexican",
    "argentinian",
    "chilean",
    "cuban",
    "australian",
    "new-zealand",
    "canadian",
    "global",
    "other",
]

# ---------------------------------------------------------------------------
# Isms / film movements / aesthetic schools
# ---------------------------------------------------------------------------
ISMS = [
    # Classical schools
    "realism",
    "formalism",
    "classicism",
    "naturalism",
    "romanticism",
    "expressionism",
    "impressionism",
    "surrealism",
    "symbolism",
    "constructivism",
    "cubism",
    "dada",
    "absurdist",
    # Named movements
    "german-expressionism",
    "soviet-montage",
    "french-impressionism",
    "italian-neorealism",
    "french-new-wave",
    "british-new-wave",
    "czech-new-wave",
    "japanese-new-wave",
    "new-german-cinema",
    "hong-kong-new-wave",
    "taiwan-new-cinema",
    "korean-new-wave",
    "iranian-new-wave",
    "dogme-95",
    "cinema-verite",
    "direct-cinema",
    "free-cinema",
    "third-cinema",
    "parallel-cinema",
    "la-nouvelle-vague",
    "cinema-novo",
    "yugoslav-black-wave",
    "mumblecore",
    "slow-cinema",
    "elevated-horror",
    "found-footage",
    "arthouse",
    # Aesthetic modes
    "modernism",
    "postmodernism",
    "minimalism",
    "maximalism",
    "brutalism",
    "futurism",
    "magical-realism",
    "hyperrealism",
    "documentary-realism",
    "poetic-realism",
    "social-realism",
    "kitchen-sink",
    "camp",
    "kitsch",
    "baroque",
    "gothic",
    "noir",
    "neo-noir",
    "tech-noir",
    "psychedelia",
    "dream-logic",
    "other",
]

# ---------------------------------------------------------------------------
# Visual styles / mediums / look
# ---------------------------------------------------------------------------
VISUAL_STYLES = [
    "live-action",
    "anime",
    "2d-animation",
    "3d-cgi",
    "stop-motion",
    "rotoscope",
    "mixed-media",
    "documentary-realism",
    "fashion-editorial",
    "commercial-gloss",
    "indie-raw",
    "noir",
    "neo-noir",
    "surreal",
    "hyperreal",
    "painterly",
    "graphic-novel",
    "lo-fi",
    "vhs",
    "16mm",
    "35mm",
    "70mm",
    "imax",
    "anamorphic",
    "found-footage",
    "handheld-doc",
    "studio-polish",
    "desaturated",
    "high-contrast",
    "pastel",
    "neon-noir",
    "other",
]

# ---------------------------------------------------------------------------
# Themes / vibes / internet aesthetics
# ---------------------------------------------------------------------------
THEMES = [
    "dreamcore",
    "weirdcore",
    "liminal",
    "nostalgia",
    "solarpunk",
    "cyberpunk",
    "steampunk",
    "dieselpunk",
    "vaporwave",
    "synthwave",
    "cottagecore",
    "dark-academia",
    "light-academia",
    "brutalism",
    "minimalism",
    "maximalism",
    "dystopian",
    "utopian",
    "romance",
    "horror",
    "comedy",
    "action",
    "sports-glory",
    "luxury",
    "street",
    "nature",
    "urban",
    "suburban",
    "domestic",
    "ritual",
    "isolation",
    "community",
    "technology",
    "body",
    "memory",
    "identity",
    "power",
    "faith",
    "other",
]

# ---------------------------------------------------------------------------
# Genres (broader than theme)
# ---------------------------------------------------------------------------
GENRES = [
    "drama",
    "comedy",
    "action",
    "thriller",
    "horror",
    "romance",
    "sci-fi",
    "fantasy",
    "western",
    "war",
    "crime",
    "mystery",
    "adventure",
    "sports",
    "musical",
    "biopic",
    "historical",
    "period",
    "experimental",
    "art-house",
    "advertising",
    "fashion",
    "music-video",
    "documentary",
    "other",
]

# ---------------------------------------------------------------------------
# Shape / graphic links (composition geometry for visual rhyming)
# ---------------------------------------------------------------------------
SHAPES = [
    "circle",
    "square",
    "triangle",
    "rectangle",
    "diagonal",
    "curve",
    "spiral",
    "grid",
    "silhouette-shape",
    "negative-cutout",
    "repeating-pattern",
    "symmetry-axis",
    "vanishing-point",
    "frame-edge",
    "other",
]

# ---------------------------------------------------------------------------
# EyeCandy-style visual techniques (primary browse axis)
# Multi-label — a shot can have several.
# ---------------------------------------------------------------------------
TECHNIQUES = [
    # Camera / movement
    "aerial",
    "arc",
    "bolt-cam",
    "boomerang",
    "bullet-time",
    "camera-roll",
    "crash-cut",
    "dolly",
    "dolly-zoom",
    "double-dolly",
    "falling",
    "fast-motion",
    "first-person",
    "fixed-cam",
    "flash-cut",
    "fpv-drone",
    "freeze-frame",
    "handheld",
    "jump-cut",
    "lazy-susan",
    "locked-on",
    "match-cut",
    "match-motion",
    "pan",
    "parallax",
    "pass-through",
    "pedestal",
    "quick-cuts",
    "slow-motion",
    "snorricam",
    "speed-ramp",
    "step-print",
    "stutter",
    "tilt",
    "tracking",
    "trucking",
    "wandering",
    "whip-pan",
    "zoom",
    # Framing / angle
    "central-framing",
    "close-up",
    "cut-ins",
    "dutch-angle",
    "ground-level",
    "high-angle",
    "low-angle",
    "overhead",
    "over-the-shoulder",
    "profile",
    "two-shot",
    "ultra-wide",
    "wide-shot",
    "worms-eye",
    # Optical / lens
    "fisheye",
    "focal-shift",
    "magnification",
    "probe",
    "shallow-focus",
    "split-diopter",
    "tilt-shift",
    "vignette",
    # Light / atmosphere
    "halation",
    "hard-light",
    "haze",
    "light-flash",
    "silhouette",
    "spotlight",
    # Effects / style
    "altered-state",
    "animation",
    "anthropomorphism",
    "architexture",
    "bts",
    "cinemagraph",
    "collage",
    "color-shift",
    "conveyor",
    "datamosh",
    "diorama",
    "distortions",
    "double-exposure",
    "dreamcore",
    "duplication",
    "dystopian",
    "echo-print",
    "epiphany",
    "feedback",
    "floating-ui",
    "fourth-wall",
    "generative",
    "gesture",
    "infinite-loop",
    "interview",
    "kaleidoscope",
    "levitation",
    "magical-realism",
    "masking",
    "match-split",
    "maximalism",
    "mixed-media",
    "morphing",
    "motion-blur",
    "night-vision",
    "object-portal",
    "object-pov",
    "omnidirectional",
    "photogrammetry",
    "photography",
    "pixel-art",
    "product",
    "projections",
    "ratio-switch",
    "reflections",
    "scale-shift",
    "screen-in-screen",
    "set-transition",
    "shadow-box",
    "slit-scan",
    "split-screen",
    "stop-motion",
    "stylistic-suck",
    "tableau",
    "thermal",
    "transformation",
    "transitions",
    "typography",
    "underwater",
    "video-game",
    "video-portraits",
    "vintage",
    "void",
    "voyeur",
    "weirdcore",
    "wigglegram",
    "x-ray",
    "zoetrope",
]

TECHNIQUE_SET = set(TECHNIQUES)

# Grouped for UI browse (EyeCandy-like sections)
TECHNIQUE_GROUPS: dict[str, list[str]] = {
    "Camera & Movement": [
        "aerial",
        "arc",
        "bolt-cam",
        "boomerang",
        "bullet-time",
        "camera-roll",
        "crash-cut",
        "dolly",
        "dolly-zoom",
        "double-dolly",
        "falling",
        "fast-motion",
        "first-person",
        "fixed-cam",
        "flash-cut",
        "fpv-drone",
        "freeze-frame",
        "handheld",
        "jump-cut",
        "lazy-susan",
        "locked-on",
        "match-cut",
        "match-motion",
        "pan",
        "parallax",
        "pass-through",
        "pedestal",
        "quick-cuts",
        "slow-motion",
        "snorricam",
        "speed-ramp",
        "step-print",
        "stutter",
        "tilt",
        "tracking",
        "trucking",
        "wandering",
        "whip-pan",
        "zoom",
    ],
    "Framing & Angle": [
        "central-framing",
        "close-up",
        "cut-ins",
        "dutch-angle",
        "ground-level",
        "high-angle",
        "low-angle",
        "overhead",
        "over-the-shoulder",
        "profile",
        "two-shot",
        "ultra-wide",
        "wide-shot",
        "worms-eye",
    ],
    "Lens & Optics": [
        "fisheye",
        "focal-shift",
        "magnification",
        "probe",
        "shallow-focus",
        "split-diopter",
        "tilt-shift",
        "vignette",
    ],
    "Light & Atmosphere": [
        "halation",
        "hard-light",
        "haze",
        "light-flash",
        "silhouette",
        "spotlight",
    ],
    "Style & Effects": [
        "altered-state",
        "animation",
        "anthropomorphism",
        "architexture",
        "bts",
        "cinemagraph",
        "collage",
        "color-shift",
        "conveyor",
        "datamosh",
        "diorama",
        "distortions",
        "double-exposure",
        "dreamcore",
        "duplication",
        "dystopian",
        "echo-print",
        "epiphany",
        "feedback",
        "floating-ui",
        "fourth-wall",
        "generative",
        "gesture",
        "infinite-loop",
        "interview",
        "kaleidoscope",
        "levitation",
        "magical-realism",
        "masking",
        "match-split",
        "maximalism",
        "mixed-media",
        "morphing",
        "motion-blur",
        "night-vision",
        "object-portal",
        "object-pov",
        "omnidirectional",
        "photogrammetry",
        "photography",
        "pixel-art",
        "product",
        "projections",
        "ratio-switch",
        "reflections",
        "scale-shift",
        "screen-in-screen",
        "set-transition",
        "shadow-box",
        "slit-scan",
        "split-screen",
        "stop-motion",
        "stylistic-suck",
        "tableau",
        "thermal",
        "transformation",
        "transitions",
        "typography",
        "underwater",
        "video-game",
        "video-portraits",
        "vintage",
        "void",
        "voyeur",
        "weirdcore",
        "wigglegram",
        "x-ray",
        "zoetrope",
    ],
}


def normalize_technique(raw: str) -> str | None:
    clean = raw.lower().strip().replace("_", "-").replace(" ", "-")
    clean = clean.replace("over-shoulder", "over-the-shoulder")
    clean = clean.replace("worm's-eye", "worms-eye").replace("worms-eye-view", "worms-eye")
    clean = clean.replace("bird's-eye", "birds-eye")
    if clean in TECHNIQUE_SET:
        return clean
    # soft aliases
    aliases = {
        "ots": "over-the-shoulder",
        "ecu": "close-up",
        "xcu": "close-up",
        "pov": "first-person",
        "fpv": "fpv-drone",
        "vertigo": "dolly-zoom",
        "zolly": "dolly-zoom",
        "crash-zoom": "zoom",
        "push-in": "dolly",
        "pull-out": "dolly",
        "steadicam": "tracking",
        "gimbal": "tracking",
        "drone": "aerial",
        "dutch": "dutch-angle",
        "canted": "dutch-angle",
        "birds-eye": "overhead",
        "top-down": "overhead",
        "macro": "magnification",
        "rack-focus": "focal-shift",
        "focus-pull": "focal-shift",
        "anamorphic": "wide-shot",
        "timelapse": "fast-motion",
        "time-lapse": "fast-motion",
        "slo-mo": "slow-motion",
        "slomo": "slow-motion",
        "whip": "whip-pan",
        "wiggle": "wigglegram",
        # EyeCandy site slugs
        "dolly-shot": "dolly",
        "arc-movement": "arc",
        "crash-transition": "crash-cut",
        "crash-zoom": "zoom",
        "object-pov": "first-person",
        "extreme-close-up": "close-up",
        "echo-printing": "step-print",
        "infinite-zoom": "zoom",
        "scale-shift": "dolly-zoom",
        "trim-editing": "quick-cuts",
        "as-object": "anthropomorphism",
    }
    if clean in aliases:
        return aliases[clean]
    # Keep unknown EyeCandy slugs so mirrored folders still tag correctly
    if re.fullmatch(r"[a-z0-9]+(?:-[a-z0-9]+)*", clean) and len(clean) > 2:
        return clean
    return None


def normalize_slug(raw: str, allowed: set[str] | list[str], *, default: str | None = None) -> str | None:
    clean = raw.lower().strip().replace("_", "-").replace(" ", "-")
    allowed_set = set(allowed)
    if clean in allowed_set:
        return clean
    return default


def normalize_composition(raw: str | None, *, default: str = "other") -> str:
    """Map freeform / alias composition labels onto COMPOSITIONS."""
    if not raw:
        return default
    clean = raw.lower().strip().replace("_", "-").replace(" ", "-")
    clean = clean.replace("composition-", "").replace("-composition", "")
    if clean in COMPOSITIONS:
        return clean
    if clean in COMPOSITION_ALIASES:
        return COMPOSITION_ALIASES[clean]
    # Soft contains for verbose VLM answers
    for alias, slug in COMPOSITION_ALIASES.items():
        if alias in clean or clean in alias:
            return slug
    for slug in COMPOSITIONS:
        if slug != "other" and (slug in clean or clean in slug):
            return slug
    return default


def normalize_list(raw: list[str] | None, allowed: set[str] | list[str], *, limit: int = 6) -> list[str]:
    out: list[str] = []
    allowed_set = set(allowed)
    for t in raw or []:
        n = normalize_slug(str(t), allowed_set)
        if n and n not in out:
            out.append(n)
        if len(out) >= limit:
            break
    return out


def normalize_techniques(raw: list[str] | None, *, limit: int = 8) -> list[str]:
    out: list[str] = []
    for t in raw or []:
        n = normalize_technique(str(t))
        if n and n not in out:
            out.append(n)
        if len(out) >= limit:
            break
    return out


def taxonomy_payload() -> dict:
    return {
        "shot_types": SHOT_TYPES,
        "camera_movements": CAMERA_MOVEMENTS,
        "camera_angles": CAMERA_ANGLES,
        "lighting_styles": LIGHTING_STYLES,
        "compositions": COMPOSITIONS,
        "lens_looks": LENS_LOOKS,
        "color_grades": COLOR_GRADES,
        "emotions": EMOTIONS,
        "content_formats": CONTENT_FORMATS,
        "eras": ERAS,
        "origins": ORIGINS,
        "isms": ISMS,
        "visual_styles": VISUAL_STYLES,
        "themes": THEMES,
        "genres": GENRES,
        "shapes": SHAPES,
        "techniques": TECHNIQUES,
        "technique_groups": TECHNIQUE_GROUPS,
    }
