export const FALLBACK_IDEAS = [
  {
    key: "screenmusings",
    label: "ScreenMusings",
    site_url: "https://screenmusings.org/",
    blurb: "High-quality frame grabs by film — closest free cousin to FilmGrab.",
    fit: "Best next scraper candidate.",
  },
  {
    key: "moviestillsdb",
    label: "MovieStillsDB",
    site_url: "https://www.moviestillsdb.com/",
    blurb: "1M+ community stills — also available as a built-in mirror (optional login for full-res).",
    fit: "Use Mirrors tab to pull; or save selectively here.",
  },
  {
    key: "shotcafe",
    label: "SHOT.CAFE",
    site_url: "https://shot.cafe/",
    blurb: "Curated shots with color and composition tags.",
    fit: "Check ToS before automating.",
  },
  {
    key: "stillslab",
    label: "StillsLab",
    site_url: "https://stillslab.com/",
    blurb: "Film/TV/music-video stills — subscription login on Mirrors tab.",
    fit: "Gated mirror with email + password.",
  },
  {
    key: "wikimedia-film",
    label: "Wikimedia Commons",
    site_url: "https://commons.wikimedia.org/wiki/Category:Films",
    blurb: "Public-domain and freely licensed film imagery.",
    fit: "Truly free for many PD-era items.",
  },
  {
    key: "internet-archive-film",
    label: "Internet Archive",
    site_url: "https://archive.org/details/movies",
    blurb: "Public-domain features you can download legally.",
    fit: "Pair with your own frame extracts.",
  },
  {
    key: "evanerichards",
    label: "Evan Richards",
    site_url: "https://www.evanerichards.com/",
    blurb: "Cinematography stills by film and DP.",
    fit: "Manual / careful saves.",
  },
  {
    key: "bluscreens",
    label: "Caps-a-holic / Blu-ray caps",
    site_url: "https://caps-a-holic.com/",
    blurb: "Fan screen-capture galleries organized by title.",
    fit: "Selective; ToS-sensitive.",
  },
  {
    key: "frameset",
    label: "Frame Set",
    site_url: "https://frameset.app/",
    blurb: "Curated frames across film, ads, and music video.",
    fit: "Inspiration; license your own exports.",
  },
  {
    key: "imdb-stills",
    label: "IMDb media",
    site_url: "https://www.imdb.com/",
    blurb: "Press stills attached to titles — cast and set references.",
    fit: "Manual reference only.",
  },
  {
    key: "thefilmstage-stills",
    label: "The Film Stage",
    site_url: "https://thefilmstage.com/",
    blurb: "Occasional high-res stills and frame posts.",
    fit: "Browse + save into a custom archive.",
  },
];
